[package]
name = "pixel_map"
description = "A map of pixels implemented by an MX quad tree."
version = "0.1.0"
authors = ["Troy Kinsella"]
homepage = "https://github.com/DonkulosisLabs/pixel_map_rs"
repository = "https://github.com/DonkulosisLabs/pixel_map_rs"
readme = "README.md"
license-file = "LICENSE"
edition = "2021"
keywords = ["pixel", "map", "image", "quadtree", "data-structure"]
categories = ["data-structures", "multimedia::images"]

[dependencies]
glam = "^0.23.0"
num-traits = "^0.2.15"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "set_pixel"
harness = false

[[bench]]
name = "get_pixel"
harness = false

[[bench]]
name = "visit"
harness = false

